server:
  port: 8080
  context-path: /BMS
logging:
  level:
    com.dly.dao.LevelDAO: debug
    com.dly.dao.GroupDAO: debug
    com.dly.dao.TVideoMapper: debug
    com.dly.dao.TGroupMapper: debug
   
spring:
    http:
      multipart:
        enabled: true
        max-file-size: 1024Mb 
        max-request-size: 1024Mb 
    datasource:
        url: jdbc:mysql://39.106.210.162:3306/app?characterEncoding=utf-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: lizhongshi
        password: LiZhongShi0917!
        type: com.alibaba.druid.pool.DruidDataSource 
        driver-class-name: com.mysql.jdbc.Driver   
        platform: mysql
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  

jpa:
     hibernate.ddl-auto: update
     show-sql: true
     thymeleaf:
      cache: false
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
 
    
jpush:
  config:
    appkey: c241f4c4694b35c7fc40bd7f
    masterSecret: 8e8afdd7a30f221bf681faea


   
      